name: Test

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Start Docker compose
      run: |
        docker-compose up -d
        sleep 10

    - name: Run Tests
      run: |
        docker-compose exec app nosetests app/test -vv
        docker-compose exec app casperjs test app/test
